# Generated by Django 5.2.6 on 2025-09-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
