# Generated by Django 5.2.6 on 2025-09-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(default='python', max_length=100),
            preserve_default=False,
        ),
    ]
